Repository MrTanoshii/PyWeek-34, pull requests merged in 2022-09, with the labels that each got.

#11 Basic game setup, currency & gamedata
  README.md
  run_game.py
  src/classes/__init__.py
  src/classes/gamedata.py
  src/classes/gold.py
  src/classes/research.py
  src/classes/resource.py
  src/const/__init__.py
  src/const/settings.py
  src/const/views.py
  src/interfaces/__init__.py
  src/main.py
  src/views/__init__.py
  src/views/map_view.py
Labels: documentation, enhancement, Core Feature, Optional Feature

#18 Add enemy & tower design
  docs/Game Design Doc/Enemy.md
  docs/Game Design Doc/Towers.md
Labels: documentation, Core Feature

#19 Map
  .gitignore
  resources/enemies/alien1.png
  resources/maps/floortileset.png
  resources/maps/floortileset.tsx
  resources/maps/maps.tiled-project
  resources/maps/maps.tiled-session
  resources/maps/test_map_2.json
  resources/maps/test_map_4.json
  resources/towers/anti-air-1.png
  src/classes/__init__.py
  src/classes/enemy.py
  src/classes/enemy_handler.py
  src/classes/grid.py
  src/classes/tower.py
  src/classes/tower_handler.py
  src/classes/world.py
  src/const/__init__.py
  src/const/grid.py
  src/const/resources.py
  src/const/settings.py
  src/const/towers.py
  src/main.py
  src/views/map.py
  src/views/map_view.py
Labels: enhancement, Core Feature

#20 Implement Audio system
  docs/API Reference/Audio.md
  docs/Attribution/Audio.md
  mkdocs.yml
  src/audio/__init__.py
  src/audio/audio.py
  src/audio/resources/Space_Fighter_Loop.mp3
  src/const/__init__.py
  src/const/audio.py
  src/views/map.py
  src/views/map_view.py
Labels: bug, documentation, enhancement, Core Feature, SFX

#27 Map
  .gitignore
  resources/maps/maps.tiled-session
  resources/maps/test_map_4.json
  resources/maps/test_map_5.json
  src/classes/enemy_handler.py
  src/classes/spawner.py
  src/classes/world.py
  src/main.py
  src/views/map.py
Labels: enhancement, Core Feature

#28 Fixed the grid bug and errors from the last merge
  src/classes/grid.py
  src/classes/world.py
  src/views/map.py
Labels: bug, Core Feature

#29 Add research tree
  docs/API Reference/Research Tree.md
  src/const/__init__.py
  src/const/research_tree.py
  src/research-tree/__init__.py
  src/research-tree/research_tree.py
Labels: documentation, enhancement, Core Feature

#40 console warning messages (gold, road, outside window)
  src/const/__init__.py
  src/const/bcolors.py
  src/towers/tower_handler.py
Labels: enhancement

#43 Enemy targeting
  src/const/__init__.py
  src/const/targeting.py
  src/enemy/enemy.py
  src/enemy/enemy_handler.py
  src/towers/__init__.py
  src/towers/targeting.py
  src/towers/tower.py
  src/towers/tower_handler.py
  src/views/map.py
  src/world/spawner.py
  src/world/world.py
Labels: enhancement, Core Feature

#69 Bullet merge
  src/audio/audio.py
  src/audio/sounds/alienshoot1.wav
  src/bullet/__init__.py
  src/bullet/bullet.py
  src/const/audio.py
  src/const/debug.py
  src/const/towers.py
  src/enemy/enemy.py
  src/enemy/enemy_handler.py
  src/resources/__init__.py
  src/resources/lives.py
  src/towers/tower.py
  src/towers/tower_handler.py
  src/views/map.py
  src/world/grid.py
Labels: bug, enhancement, Core Feature, Art

#70 Window icon
  resources/icon.png
  src/const/towers.py
  src/enemy/enemy.py
  src/enemy/enemy_handler.py
  src/main.py
  src/views/map.py
Labels: enhancement, Optional Feature, Art

#76 update README.md
  README.md
Labels: documentation

#84 Bullet sprites
  src/bullet/bullet.py
  src/const/towers.py
  src/enemy/enemy_handler.py
  src/towers/sprites/Bullet_Cannon.png
  src/towers/sprites/Bullet_MG.png
  src/towers/sprites/Missile.png
  src/towers/tower.py
  src/towers/tower_handler.py
  src/views/map.py
Labels: enhancement, good first issue, Core Feature

#85 Tower selection
  src/bullet/bullet.py
  src/const/audio.py
  src/const/debug.py
  src/const/towers.py
  src/gui/buttons.py
  src/gui/gui.py
  src/towers/tower_handler.py
  src/views/map.py
  src/world/grid.py
  src/world/world.py
Labels: enhancement

#86 Menu
  resources/bg.png
  src/audio/audio.py
  src/const/__init__.py
  src/const/gui.py
  src/const/menu.py
  src/enemy/enemy_handler.py
  src/gamedata/gamedata.py
  src/gui/__init__.py
  src/gui/buttons.py
  src/gui/gui.py
  src/gui/preview.py
  src/gui/window.py
  src/main.py
  src/views/__init__.py
  src/views/main_menu.py
  src/views/map.py
  src/world/previews/draft_level_1.png
  src/world/previews/draft_level_2.png
  src/world/world.py
Labels: enhancement

#87 Implement audio increase/decrease
  docs/API Reference/Audio.md
  src/audio/audio.py
  src/const/audio.py
  src/views/map.py
Labels: documentation, enhancement, Core Feature, SFX

#88 level menu
  src/const/menu.py
  src/world/previews/draft_level_1.png
  src/world/previews/draft_level_2.png
Labels: enhancement

#91 Muting sounds stops all audio
  docs/API Reference/Audio.md
  src/audio/audio.py
  src/gui/buttons.py
  src/gui/gui.py
  src/views/map.py
Labels: bug, enhancement, Core Feature, SFX

#98 Reset gold
  src/bullet/bullet.py
  src/const/towers.py
  src/const/waves.py
  src/enemy/enemies.py
  src/gui/gui.py
  src/gui/window.py
  src/views/main_menu.py
  src/views/map.py
Labels: bug

#103 Resize the ui blocker
  src/world/maps/draft_level_1.json
  src/world/maps/draft_level_2.json
  src/world/maps/draft_level_3.json
  src/world/maps/draft_level_4.json
  src/world/maps/draft_level_5.json
  src/world/maps/draft_level_secret_duck.json
  src/world/maps/draft_level_secret_penguin.json
  src/world/maps/draft_level_secret_turtle.json
Labels: good first issue, Core Feature

#108 fixed notification time to live in tower build selection
  src/gui/gui.py
  src/gui/notifications.py
Labels: bug
